# Copyright (c) - Graphical Playground. All rights reserved.
# For more information, see https://graphical-playground/legal
# mailto:support AT graphical-playground DOT com

name: 'Setup macOS Dependencies'
description: 'Set up macOS dependencies for GitHub Actions.'

branding:
  icon: 'command'
  color: 'gray-dark'

runs:
  using: 'composite'
  steps:
    - name: Run Setup Script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/setup-macos.sh
        ${{ github.action_path }}/setup-macos.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
