# Copyright (c) - Graphical Playground. All rights reserved.
# For more information, see https://graphical-playground/legal
# mailto:support AT graphical-playground DOT com

name: 'Setup Linux Dependencies'
description: 'Set up Linux dependencies for GitHub Actions.'

branding:
  icon: 'terminal'
  color: 'yellow'

runs:
  using: 'composite'
  steps:
    - name: Run Setup Script
      shell: bash
      run: |
        chmod +x ${{ github.action_path }}/setup-linux.sh
        ${{ github.action_path }}/setup-linux.sh
      env:
        GITHUB_TOKEN: ${{ github.token }}
